project = "mycorp1"
job_wait = 3600

[[datasets]]
name = "myevents"
prefix = "event_"
bucket = "mycorp-backups-myevents"

[[datasets]]
name = "myevents2"
prefix = "event_"
bucket = "mycorp-backups-myevents2"
